// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// read_bin
List read_bin(const std::string& filepath_x, const std::string& filepath_y, const arma::uvec& bag, const int& x_dim);
RcppExport SEXP _VBspPCA_read_bin(SEXP filepath_xSEXP, SEXP filepath_ySEXP, SEXP bagSEXP, SEXP x_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filepath_x(filepath_xSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type filepath_y(filepath_ySEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type bag(bagSEXP);
    Rcpp::traits::input_parameter< const int& >::type x_dim(x_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(read_bin(filepath_x, filepath_y, bag, x_dim));
    return rcpp_result_gen;
END_RCPP
}
// doVB_norm_woi_diag_om
Rcpp::List doVB_norm_woi_diag_om(arma::field<arma::mat> V, double lambda, const arma::vec y, const arma::umat X, const arma::uvec dims, const int& L, const std::string& constr_type, const int& maxit, const double& tau, const double& a, const double& b, const double& tol);
RcppExport SEXP _VBspPCA_doVB_norm_woi_diag_om(SEXP VSEXP, SEXP lambdaSEXP, SEXP ySEXP, SEXP XSEXP, SEXP dimsSEXP, SEXP LSEXP, SEXP constr_typeSEXP, SEXP maxitSEXP, SEXP tauSEXP, SEXP aSEXP, SEXP bSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::umat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type constr_type(constr_typeSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(doVB_norm_woi_diag_om(V, lambda, y, X, dims, L, constr_type, maxit, tau, a, b, tol));
    return rcpp_result_gen;
END_RCPP
}
// doVB_norm_woi_diag_bin
Rcpp::List doVB_norm_woi_diag_bin(arma::field<arma::mat> V, double lambda, const int N1, const std::string& readbin_x, const std::string& readbin_y, const arma::uvec dims, const int& L, const std::string& constr_type, const int& maxit, const double& tau, const double& a, const double& b, const double tol);
RcppExport SEXP _VBspPCA_doVB_norm_woi_diag_bin(SEXP VSEXP, SEXP lambdaSEXP, SEXP N1SEXP, SEXP readbin_xSEXP, SEXP readbin_ySEXP, SEXP dimsSEXP, SEXP LSEXP, SEXP constr_typeSEXP, SEXP maxitSEXP, SEXP tauSEXP, SEXP aSEXP, SEXP bSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type N1(N1SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type readbin_x(readbin_xSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type readbin_y(readbin_ySEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type constr_type(constr_typeSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(doVB_norm_woi_diag_bin(V, lambda, N1, readbin_x, readbin_y, dims, L, constr_type, maxit, tau, a, b, tol));
    return rcpp_result_gen;
END_RCPP
}
// doVB_norm_woi_diag_mtx
Rcpp::List doVB_norm_woi_diag_mtx(arma::field<arma::mat> V, double lambda, const std::string& readtxt, const arma::uvec dims, const int& L, const std::string& constr_type, const int& maxit, const double& tau, const double& a, const double& b, const double tol);
RcppExport SEXP _VBspPCA_doVB_norm_woi_diag_mtx(SEXP VSEXP, SEXP lambdaSEXP, SEXP readtxtSEXP, SEXP dimsSEXP, SEXP LSEXP, SEXP constr_typeSEXP, SEXP maxitSEXP, SEXP tauSEXP, SEXP aSEXP, SEXP bSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type readtxt(readtxtSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type constr_type(constr_typeSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(doVB_norm_woi_diag_mtx(V, lambda, readtxt, dims, L, constr_type, maxit, tau, a, b, tol));
    return rcpp_result_gen;
END_RCPP
}
// check_lr
double check_lr(const int& epoc, const arma::vec& lr_param, const std::string& lr_type);
RcppExport SEXP _VBspPCA_check_lr(SEXP epocSEXP, SEXP lr_paramSEXP, SEXP lr_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type epoc(epocSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lr_param(lr_paramSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type lr_type(lr_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(check_lr(epoc, lr_param, lr_type));
    return rcpp_result_gen;
END_RCPP
}
// obsfitloss_mtx
List obsfitloss_mtx(const std::string& readtxt, arma::mat fit, const int& n_header);
RcppExport SEXP _VBspPCA_obsfitloss_mtx(SEXP readtxtSEXP, SEXP fitSEXP, SEXP n_headerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type readtxt(readtxtSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_header(n_headerSEXP);
    rcpp_result_gen = Rcpp::wrap(obsfitloss_mtx(readtxt, fit, n_header));
    return rcpp_result_gen;
END_RCPP
}
// rowmeanvar_mtx
List rowmeanvar_mtx(const int& n_row, const int& n_col, const std::string& readtxt, const int& n_header);
RcppExport SEXP _VBspPCA_rowmeanvar_mtx(SEXP n_rowSEXP, SEXP n_colSEXP, SEXP readtxtSEXP, SEXP n_headerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type n_row(n_rowSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_col(n_colSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type readtxt(readtxtSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_header(n_headerSEXP);
    rcpp_result_gen = Rcpp::wrap(rowmeanvar_mtx(n_row, n_col, readtxt, n_header));
    return rcpp_result_gen;
END_RCPP
}
// rowfilter_mtx
void rowfilter_mtx(const std::string& readtxt, const std::string& writetxt, const arma::vec& rowind);
RcppExport SEXP _VBspPCA_rowfilter_mtx(SEXP readtxtSEXP, SEXP writetxtSEXP, SEXP rowindSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type readtxt(readtxtSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type writetxt(writetxtSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rowind(rowindSEXP);
    rowfilter_mtx(readtxt, writetxt, rowind);
    return R_NilValue;
END_RCPP
}
// read_mtx
List read_mtx(const std::string& readtxt, const arma::uvec& bag);
RcppExport SEXP _VBspPCA_read_mtx(SEXP readtxtSEXP, SEXP bagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type readtxt(readtxtSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type bag(bagSEXP);
    rcpp_result_gen = Rcpp::wrap(read_mtx(readtxt, bag));
    return rcpp_result_gen;
END_RCPP
}
// doSVB_norm_woi_diag
Rcpp::List doSVB_norm_woi_diag(arma::field<arma::mat> V, double lambda, const arma::vec& y, const arma::umat& X, const arma::uvec dims, const int& L, const std::string& constr_type, const std::string& lr_type, const arma::vec& lr_param, const int& bsize, const int& iter, const double& tau, const double& a, const double& b, const bool& display_progress);
RcppExport SEXP _VBspPCA_doSVB_norm_woi_diag(SEXP VSEXP, SEXP lambdaSEXP, SEXP ySEXP, SEXP XSEXP, SEXP dimsSEXP, SEXP LSEXP, SEXP constr_typeSEXP, SEXP lr_typeSEXP, SEXP lr_paramSEXP, SEXP bsizeSEXP, SEXP iterSEXP, SEXP tauSEXP, SEXP aSEXP, SEXP bSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type constr_type(constr_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type lr_type(lr_typeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lr_param(lr_paramSEXP);
    Rcpp::traits::input_parameter< const int& >::type bsize(bsizeSEXP);
    Rcpp::traits::input_parameter< const int& >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const bool& >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(doSVB_norm_woi_diag(V, lambda, y, X, dims, L, constr_type, lr_type, lr_param, bsize, iter, tau, a, b, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ra1_norm
double ra1_norm(const double& a, const double& mean, const double& sd);
RcppExport SEXP _VBspPCA_ra1_norm(SEXP aSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const double& >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(ra1_norm(a, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// doVB_norm
List doVB_norm(const arma::vec& y, const arma::uvec& rowi, const arma::uvec& coli, const int& Nr, const int& Nc, const int& L, const int& iter, const double& prior_prec, const double& a, const double& b);
RcppExport SEXP _VBspPCA_doVB_norm(SEXP ySEXP, SEXP rowiSEXP, SEXP coliSEXP, SEXP NrSEXP, SEXP NcSEXP, SEXP LSEXP, SEXP iterSEXP, SEXP prior_precSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type rowi(rowiSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type coli(coliSEXP);
    Rcpp::traits::input_parameter< const int& >::type Nr(NrSEXP);
    Rcpp::traits::input_parameter< const int& >::type Nc(NcSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type prior_prec(prior_precSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(doVB_norm(y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b));
    return rcpp_result_gen;
END_RCPP
}
// doVB_norm_s_mtx
List doVB_norm_s_mtx(const std::string& file_path, const int& Nr, const int& Nc, const double& N1, const int& L, const int& ns, const int& iter, const int& subiter, const double& prior_prec, const double& a, const double& b, const arma::vec& lr_param, const std::string& lr_type);
RcppExport SEXP _VBspPCA_doVB_norm_s_mtx(SEXP file_pathSEXP, SEXP NrSEXP, SEXP NcSEXP, SEXP N1SEXP, SEXP LSEXP, SEXP nsSEXP, SEXP iterSEXP, SEXP subiterSEXP, SEXP prior_precSEXP, SEXP aSEXP, SEXP bSEXP, SEXP lr_paramSEXP, SEXP lr_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< const int& >::type Nr(NrSEXP);
    Rcpp::traits::input_parameter< const int& >::type Nc(NcSEXP);
    Rcpp::traits::input_parameter< const double& >::type N1(N1SEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const int& >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const int& >::type subiter(subiterSEXP);
    Rcpp::traits::input_parameter< const double& >::type prior_prec(prior_precSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lr_param(lr_paramSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type lr_type(lr_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(doVB_norm_s_mtx(file_path, Nr, Nc, N1, L, ns, iter, subiter, prior_prec, a, b, lr_param, lr_type));
    return rcpp_result_gen;
END_RCPP
}
// doVB_norm_woi
List doVB_norm_woi(const arma::vec& y, const arma::uvec& rowi, const arma::uvec& coli, const int& Nr, const int& Nc, const int& L, const int& iter, const double& prior_prec, const double& a, const double& b);
RcppExport SEXP _VBspPCA_doVB_norm_woi(SEXP ySEXP, SEXP rowiSEXP, SEXP coliSEXP, SEXP NrSEXP, SEXP NcSEXP, SEXP LSEXP, SEXP iterSEXP, SEXP prior_precSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type rowi(rowiSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type coli(coliSEXP);
    Rcpp::traits::input_parameter< const int& >::type Nr(NrSEXP);
    Rcpp::traits::input_parameter< const int& >::type Nc(NcSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type prior_prec(prior_precSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(doVB_norm_woi(y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b));
    return rcpp_result_gen;
END_RCPP
}
// doVB_norm_wo_s_mtx
List doVB_norm_wo_s_mtx(const std::string& file_path, const int& Nr, const int& Nc, const double& N1, const int& L, const int& ns, const int& iter, const double& prior_prec, const double& a, const double& b, const arma::vec& lr_param, const std::string& lr_type);
RcppExport SEXP _VBspPCA_doVB_norm_wo_s_mtx(SEXP file_pathSEXP, SEXP NrSEXP, SEXP NcSEXP, SEXP N1SEXP, SEXP LSEXP, SEXP nsSEXP, SEXP iterSEXP, SEXP prior_precSEXP, SEXP aSEXP, SEXP bSEXP, SEXP lr_paramSEXP, SEXP lr_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< const int& >::type Nr(NrSEXP);
    Rcpp::traits::input_parameter< const int& >::type Nc(NcSEXP);
    Rcpp::traits::input_parameter< const double& >::type N1(N1SEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const int& >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type prior_prec(prior_precSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lr_param(lr_paramSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type lr_type(lr_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(doVB_norm_wo_s_mtx(file_path, Nr, Nc, N1, L, ns, iter, prior_prec, a, b, lr_param, lr_type));
    return rcpp_result_gen;
END_RCPP
}
// doVB_norm_woi_diag
Rcpp::List doVB_norm_woi_diag(arma::field<arma::mat> V, double lambda, const arma::vec& y, const arma::umat& X, const arma::uvec dims, const int& L, const std::string& constr_type, const int& iter, const double& tau, const double& a, const double& b, const bool& display_progress);
RcppExport SEXP _VBspPCA_doVB_norm_woi_diag(SEXP VSEXP, SEXP lambdaSEXP, SEXP ySEXP, SEXP XSEXP, SEXP dimsSEXP, SEXP LSEXP, SEXP constr_typeSEXP, SEXP iterSEXP, SEXP tauSEXP, SEXP aSEXP, SEXP bSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type constr_type(constr_typeSEXP);
    Rcpp::traits::input_parameter< const int& >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const bool& >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(doVB_norm_woi_diag(V, lambda, y, X, dims, L, constr_type, iter, tau, a, b, display_progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VBspPCA_read_bin", (DL_FUNC) &_VBspPCA_read_bin, 4},
    {"_VBspPCA_doVB_norm_woi_diag_om", (DL_FUNC) &_VBspPCA_doVB_norm_woi_diag_om, 12},
    {"_VBspPCA_doVB_norm_woi_diag_bin", (DL_FUNC) &_VBspPCA_doVB_norm_woi_diag_bin, 13},
    {"_VBspPCA_doVB_norm_woi_diag_mtx", (DL_FUNC) &_VBspPCA_doVB_norm_woi_diag_mtx, 11},
    {"_VBspPCA_check_lr", (DL_FUNC) &_VBspPCA_check_lr, 3},
    {"_VBspPCA_obsfitloss_mtx", (DL_FUNC) &_VBspPCA_obsfitloss_mtx, 3},
    {"_VBspPCA_rowmeanvar_mtx", (DL_FUNC) &_VBspPCA_rowmeanvar_mtx, 4},
    {"_VBspPCA_rowfilter_mtx", (DL_FUNC) &_VBspPCA_rowfilter_mtx, 3},
    {"_VBspPCA_read_mtx", (DL_FUNC) &_VBspPCA_read_mtx, 2},
    {"_VBspPCA_doSVB_norm_woi_diag", (DL_FUNC) &_VBspPCA_doSVB_norm_woi_diag, 15},
    {"_VBspPCA_ra1_norm", (DL_FUNC) &_VBspPCA_ra1_norm, 3},
    {"_VBspPCA_doVB_norm", (DL_FUNC) &_VBspPCA_doVB_norm, 10},
    {"_VBspPCA_doVB_norm_s_mtx", (DL_FUNC) &_VBspPCA_doVB_norm_s_mtx, 13},
    {"_VBspPCA_doVB_norm_woi", (DL_FUNC) &_VBspPCA_doVB_norm_woi, 10},
    {"_VBspPCA_doVB_norm_wo_s_mtx", (DL_FUNC) &_VBspPCA_doVB_norm_wo_s_mtx, 12},
    {"_VBspPCA_doVB_norm_woi_diag", (DL_FUNC) &_VBspPCA_doVB_norm_woi_diag, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_VBspPCA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
