# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_mtx <- function(readtxt, bag) {
    .Call(`_VBspPCA_read_mtx`, readtxt, bag)
}

ra1_norm <- function(a, mean, sd) {
    .Call(`_VBspPCA_ra1_norm`, a, mean, sd)
}

doVB_norm <- function(y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b) {
    .Call(`_VBspPCA_doVB_norm`, y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b)
}

doVB_norm_s_mtx <- function(file_path, Nr, Nc, N1, L, ns, iter, subiter, prior_prec, a, b, delay, forgetting) {
    .Call(`_VBspPCA_doVB_norm_s_mtx`, file_path, Nr, Nc, N1, L, ns, iter, subiter, prior_prec, a, b, delay, forgetting)
}

doVB_norm_woi <- function(y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b) {
    .Call(`_VBspPCA_doVB_norm_woi`, y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b)
}

doVB_norm_wo_s_mtx <- function(file_path, Nr, Nc, N1, L, ns, iter, prior_prec, a, b, delay, forgetting) {
    .Call(`_VBspPCA_doVB_norm_wo_s_mtx`, file_path, Nr, Nc, N1, L, ns, iter, prior_prec, a, b, delay, forgetting)
}

