# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doVB_norm <- function(y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b) {
    .Call(`_VBspPCA_doVB_norm`, y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b)
}

