# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doVB_norm_woi_diag_om <- function(V, lambda, y, X, dims, L, constr_type, iter, tau, a, b, display_progress) {
    .Call(`_VBspPCA_doVB_norm_woi_diag_om`, V, lambda, y, X, dims, L, constr_type, iter, tau, a, b, display_progress)
}

doVB_norm_woi_diag_mtx <- function(V, lambda, readtxt, dims, N1, N, L, constr_type, iter, tau, a, b, display_progress) {
    .Call(`_VBspPCA_doVB_norm_woi_diag_mtx`, V, lambda, readtxt, dims, N1, N, L, constr_type, iter, tau, a, b, display_progress)
}

check_lr <- function(epoc, lr_param, lr_type) {
    .Call(`_VBspPCA_check_lr`, epoc, lr_param, lr_type)
}

read_mtx <- function(readtxt, bag) {
    .Call(`_VBspPCA_read_mtx`, readtxt, bag)
}

doSVB_norm_woi_diag <- function(V, lambda, y, X, dims, L, constr_type, lr_type, lr_param, bsize, iter, tau, a, b, display_progress) {
    .Call(`_VBspPCA_doSVB_norm_woi_diag`, V, lambda, y, X, dims, L, constr_type, lr_type, lr_param, bsize, iter, tau, a, b, display_progress)
}

ra1_norm <- function(a, mean, sd) {
    .Call(`_VBspPCA_ra1_norm`, a, mean, sd)
}

doVB_norm <- function(y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b) {
    .Call(`_VBspPCA_doVB_norm`, y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b)
}

doVB_norm_s_mtx <- function(file_path, Nr, Nc, N1, L, ns, iter, subiter, prior_prec, a, b, lr_param, lr_type) {
    .Call(`_VBspPCA_doVB_norm_s_mtx`, file_path, Nr, Nc, N1, L, ns, iter, subiter, prior_prec, a, b, lr_param, lr_type)
}

doVB_norm_woi <- function(y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b) {
    .Call(`_VBspPCA_doVB_norm_woi`, y, rowi, coli, Nr, Nc, L, iter, prior_prec, a, b)
}

doVB_norm_wo_s_mtx <- function(file_path, Nr, Nc, N1, L, ns, iter, prior_prec, a, b, lr_param, lr_type) {
    .Call(`_VBspPCA_doVB_norm_wo_s_mtx`, file_path, Nr, Nc, N1, L, ns, iter, prior_prec, a, b, lr_param, lr_type)
}

doVB_norm_woi_diag <- function(V, lambda, y, X, dims, L, constr_type, iter, tau, a, b, display_progress) {
    .Call(`_VBspPCA_doVB_norm_woi_diag`, V, lambda, y, X, dims, L, constr_type, iter, tau, a, b, display_progress)
}

